%YAML:1.0
#--------------------------------------------------------------------------------------------
# IMU Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Timestamp shift. Timage = Timu + image_delay
Camera.delaytoimu: 0

# acc = acc*9.8, if below is 1
IMU.multiplyG: 0

# camera-imu frame transformation, Pi = Tic * Pc
Camera.Tbc:
    [-0.9995250378696743, 0.029615343885863205, -0.008522328211654736, 0.04727988224914392,
    0.0075019185074052044, -0.03439736061393144, -0.9993800792498829, -0.047443232143367084,
    -0.02989013031643309, -0.998969345370175, 0.03415885127385616, -0.0681999605066297,
    0.0, 0.0, 0.0, 1.0]

# Local Window size
LocalMapping.LocalWindowSize: 10
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 190.97847715128717
Camera.fy: 190.9733070521226
Camera.cx: 254.93170605935475
Camera.cy: 256.8974428996504

Camera.k1: 0.0034823894022493434
Camera.k2: 0.0007150348452162257
Camera.p1: -0.0020532361418706202
Camera.p2: 0.00020293673591811182
Camera.k3: 0

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 512

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500



